apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  # 我的rds用户名admin 和我的rds密码的 编码Base64 应该是 YWRtaW4= 和 QVdTbXlzcWw5NTAyMDY=
  mysql-username: YWRtaW4=
  mysql-password: QVdTbXlzcWw5NTAyMDY=
